### ISSUE TITLE
【20161120】Mac 下 ReactNative 打包 Android apk

### ISSUE THREAD

**Issue by zhongxia245** [zhongxia245/One-Day-One-Tip#52]
时间：2016-11-20 09:17:07
地址：https://github.com/zhongxia245/blog/issues/52

>Mac 下 ReactNative如何打包构建Android apk 的应用。该文章还差一个 打包发布到各个平台的教程 

## 总结
1. 打包 jsbundle代码
2. 生成签名
3. 添加签名到app中
4. 打包成apk（打包前也可以先运行安装在手机上测试）

---

## 把JS代码，打包成 index.android.jsbundle
参考文章：[ReactNative打离线包-android篇](https://segmentfault.com/a/1190000004192816)

```
react-native bundle --entry-file demo/index.js --bundle-output ./android/app/src/main/assets/index.android.jsbundle --platform android --assets-dest ./android/app/src/main/res/ --dev false
```

## 打包APK
[《官网打包APK教程》](http://facebook.github.io/react-native/docs/signed-apk-android.html)

### 1. 生成签名
生成一个有效期10000天的证书，证书为： my-release-key.keystore
```
keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000
```

***不要把证书提交到版本控制系统***
>Note: Remember to keep your keystore file private and never commit it to version control.

### 2. 配置打包时的签名

把 证书复制到 android/app  目录下

Edit the file ~/.gradle/gradle.properties and add the following (replace ***** with the correct keystore password, alias and key password)

在 gradle.properties 里面添加以下配置
>gradle.properties 文件是在 android的根目录下。 官网上的文件位置是错误的。（或者说，我理解错误）

```java
MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=*****
MYAPP_RELEASE_KEY_PASSWORD=*****
```

These are going to be global gradle variables, which we can later use in our gradle config to sign our app.

### 3. 添加签名
Adding signing config to your app's gradle config 
Edit the file android/app/build.gradle in your project folder and add the signing config,

修改 android/app/build.gradle 添加签名
```
...
android {
    ...
    defaultConfig { ... }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
        }
    }
}
...
```

### 4. 减小打包apk的大小

Enabling Proguard to reduce the size of the APK (optional) 
Proguard is a tool that can slightly reduce the size of the APK. It does this by stripping parts of the React Native Java bytecode (and its dependencies) that your app is not using.

IMPORTANT: Make sure to thoroughly test your app if you've enabled Proguard. Proguard often requires configuration specific to each native library you're using. See app/proguard-rules.pro.

***修改文件**：android/app/build.gradle*
>To enable Proguard, edit android/app/build.gradle:
```
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
```

### 5. 发布前测试应用是否有问题
```
react-native run-android --variant=release
```

### 5. 生成apk

生成的apk文件在， android/app/build/outputs/apk/ 下
```
cd android && ./gradlew assembleRelease
```
![](http://ww4.sinaimg.cn/large/006y8mN6gw1f9ylcbfvuuj31480din1y.jpg)

### 6. apk文件位置
```
android/app/build/outputs/apk
```

### 7. 安装apk文件
```
adb install app-release.apk
```
app-release 是发布版的apk文件。

**Comment by liujb** [comment]
Nice, thanks..
